// Felucca — escort givers.
//
// GENERATED by tools/convert-servuo.cjs from Spawns/felucca.xml (BaseEscortable spawns). Do not edit by hand;
// re-run the converter. Registers under "populate:felucca", the verb the .admin
// "Populate Felucca" button sends.

globalThis.Pack = globalThis.Pack || { spawnSets: {}, npcs: {}, decoSets: {}, doorRegions: {} };
Pack.escorts = Pack.escorts || {};

Pack.npcs["populate:felucca"] = (Pack.npcs["populate:felucca"] || []).concat([
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3645,"y":2661,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3646,"y":2661,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3647,"y":2661,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3038,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3039,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3040,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a peasant","x":1304,"y":1826,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1351,"y":1816,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1483,"y":1760,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":1484,"y":1760,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":1485,"y":1760,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":573,"y":2245,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":574,"y":2245,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":575,"y":2245,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1372,"y":3912,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":1373,"y":3912,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":1374,"y":3912,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3815,"y":1217,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3816,"y":1217,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3817,"y":1217,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":2994,"y":3451,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":2995,"y":3451,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":2996,"y":3451,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering healer","x":1333,"y":1808,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wedding traveller","x":1295,"y":1773,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3646,"y":2668,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3647,"y":2668,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3648,"y":2668,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":5308,"y":1372,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1126,"y":3688,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":1127,"y":3688,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":1128,"y":3688,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":631,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":632,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":633,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":673,"y":2235,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":674,"y":2235,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":675,"y":2235,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":2993,"y":3450,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":2994,"y":3450,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":2995,"y":3450,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3749,"y":1404,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3750,"y":1404,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3751,"y":1404,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":4398,"y":1049,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":4399,"y":1049,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":4400,"y":1049,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":3041,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":3042,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":3043,"y":827,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":631,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":632,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":633,"y":883,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":2068,"y":2854,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":2069,"y":2854,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":2070,"y":2854,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1372,"y":3916,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":1373,"y":3916,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":1374,"y":3916,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a noble","x":1126,"y":3687,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a seeker of adventure","x":1127,"y":3687,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a wandering mage","x":1128,"y":3687,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
  {"body":400,"notoriety":1,"hits":60,"name":"a merchant","x":1434,"y":1717,"z":0,"equipment":[{"graphic":7939,"layer":22,"hue":900},{"graphic":8251,"layer":11,"hue":1109}]},
]);

Pack.escorts["3645,2661"] = {"reward":[500,1000]};
Pack.escorts["3646,2661"] = {"reward":[500,1000]};
Pack.escorts["3647,2661"] = {"reward":[500,1000]};
Pack.escorts["3038,827"] = {"reward":[500,1000]};
Pack.escorts["3039,827"] = {"reward":[500,1000]};
Pack.escorts["3040,827"] = {"reward":[500,1000]};
Pack.escorts["1304,1826"] = {"reward":[500,1000]};
Pack.escorts["1351,1816"] = {"reward":[500,1000]};
Pack.escorts["1483,1760"] = {"reward":[500,1000]};
Pack.escorts["1484,1760"] = {"reward":[500,1000]};
Pack.escorts["1485,1760"] = {"reward":[500,1000]};
Pack.escorts["573,2245"] = {"reward":[500,1000]};
Pack.escorts["574,2245"] = {"reward":[500,1000]};
Pack.escorts["575,2245"] = {"reward":[500,1000]};
Pack.escorts["1372,3912"] = {"reward":[500,1000]};
Pack.escorts["1373,3912"] = {"reward":[500,1000]};
Pack.escorts["1374,3912"] = {"reward":[500,1000]};
Pack.escorts["3815,1217"] = {"reward":[500,1000]};
Pack.escorts["3816,1217"] = {"reward":[500,1000]};
Pack.escorts["3817,1217"] = {"reward":[500,1000]};
Pack.escorts["2994,3451"] = {"reward":[500,1000]};
Pack.escorts["2995,3451"] = {"reward":[500,1000]};
Pack.escorts["2996,3451"] = {"reward":[500,1000]};
Pack.escorts["1333,1808"] = {"reward":[500,1000]};
Pack.escorts["1295,1773"] = {"reward":[500,1000]};
Pack.escorts["3646,2668"] = {"reward":[500,1000]};
Pack.escorts["3647,2668"] = {"reward":[500,1000]};
Pack.escorts["3648,2668"] = {"reward":[500,1000]};
Pack.escorts["5308,1372"] = {"reward":[500,1000]};
Pack.escorts["1126,3688"] = {"reward":[500,1000]};
Pack.escorts["1127,3688"] = {"reward":[500,1000]};
Pack.escorts["1128,3688"] = {"reward":[500,1000]};
Pack.escorts["631,883"] = {"reward":[500,1000]};
Pack.escorts["632,883"] = {"reward":[500,1000]};
Pack.escorts["633,883"] = {"reward":[500,1000]};
Pack.escorts["673,2235"] = {"reward":[500,1000]};
Pack.escorts["674,2235"] = {"reward":[500,1000]};
Pack.escorts["675,2235"] = {"reward":[500,1000]};
Pack.escorts["2993,3450"] = {"reward":[500,1000]};
Pack.escorts["2994,3450"] = {"reward":[500,1000]};
Pack.escorts["2995,3450"] = {"reward":[500,1000]};
Pack.escorts["3749,1404"] = {"reward":[500,1000]};
Pack.escorts["3750,1404"] = {"reward":[500,1000]};
Pack.escorts["3751,1404"] = {"reward":[500,1000]};
Pack.escorts["4398,1049"] = {"reward":[500,1000]};
Pack.escorts["4399,1049"] = {"reward":[500,1000]};
Pack.escorts["4400,1049"] = {"reward":[500,1000]};
Pack.escorts["3041,827"] = {"reward":[500,1000]};
Pack.escorts["3042,827"] = {"reward":[500,1000]};
Pack.escorts["3043,827"] = {"reward":[500,1000]};
Pack.escorts["2068,2854"] = {"reward":[500,1000]};
Pack.escorts["2069,2854"] = {"reward":[500,1000]};
Pack.escorts["2070,2854"] = {"reward":[500,1000]};
Pack.escorts["1372,3916"] = {"reward":[500,1000]};
Pack.escorts["1373,3916"] = {"reward":[500,1000]};
Pack.escorts["1374,3916"] = {"reward":[500,1000]};
Pack.escorts["1126,3687"] = {"reward":[500,1000]};
Pack.escorts["1127,3687"] = {"reward":[500,1000]};
Pack.escorts["1128,3687"] = {"reward":[500,1000]};
Pack.escorts["1434,1717"] = {"reward":[500,1000]};
